<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NoWarn>IDE0130;IDE0047;CA1822</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../src/server/server.csproj"/>
    </ItemGroup>

</Project>
